config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :product_related_products
  resources :retailers do
    collection do
      get 'create_empty_record'
      get 'delete_ajax'
      post 'retailer_table'
      get 'geocode_addresses'
    end
  end

  get 'secure_site/wholesale_page'

  resources :coupon_usages

  resources :coupons do
    collection do
      get 'create_empty_record'
      post 'coupon_table'
      get 'delete_ajax'
      delete 'delete'
      #  put "index"
      put 'update'
    end
  end

  resources :cart do
    collection do
      post 'update'
    end
  end

  resources :order_items do
    collection do
      get 'create_empty_record'
    end
  end

  resources :orders do
    collection do
      get 'show'
      get 'create_empty_record'
      get 'create_order'
      get 'enter_order'
      post 'enter_order'
      get 'order_success'
      get 'invoice_slip'
      get 'user_orders'
      get 'resend_invoice'
      post 'order_table'
      post 'user_order_table'
      get 'express_purchase'
      get 'product_list_report'
      get 'customer_sales_report'
      get 'invoice_list_report'
      get 'receipt_list_report'
    end
  end

  resources :product_details do
    collection do
      get 'create_empty_record'
      get 'duplicate_record'
      post 'product_details_table'
      get 'delete_ajax'
      delete 'delete'
    end
  end

  resources :suppliers do
    collection do
      get 'create_empty_record'
    end
  end

  resources :products do
    collection do
      get 'create_empty_record'
      post 'product_table'
      get 'show_detail'
      post 'render_category_div'
      get 'render_image_section'
      get 'delete_ajax'
      get 'generate_inventory_report'
      post 'update_checkbox_tag'
      post 'add_image'
      get 'edit_picture'
      get 'edit_picture_swatch'
      post 'update_image_order'
      get 'product_preferences'
      post 'add_image_system'
      get 'reprocess_product_images'
      post 'sort'
      post 'update_related_order'
      get 'product_search'
      post 'update_related_list'
      post 'render_related_section'
      get 'render_swatch_picture'
      get 'clean_product_details'
      get 'activate_all_products'
      get 'clear_product_inventory_and_make_all_inactive'
      get 'hide_inactive_inventory'
      get 'search_fields'
    end
  end

  resources :product_related_products do
    collection do
      delete 'delete'
    end
  end

  match '/site/show_products' => 'site#show_products', via: :get
  match '/site/product_detail' => 'site#product_detail', via: :get
  match '/site/add_to_cart' => 'site#add_to_cart', via: :get
  match '/site/show_cart' => 'site#show_cart', via: :get
  match '/site/empty_cart' => 'site#empty_cart', via: :get
  match '/site/get_sizes_for_color' => 'site#get_sizes_for_color', via: :get
  match '/site/get_shopping_cart_info' => 'site#get_shopping_cart_info', via: :get
  match '/site/check_out' => 'site#check_out', via: :get
  match '/site/cart_update' => 'site#cart_update', via: %i[get put]
  match '/site/increment_cart_item' => 'site#increment_cart_item', via: :get
  match '/site/decrement_cart_item' => 'site#decrement_cart_item', via: :get
  match '/site/delete_cart_item' => 'site#delete_cart_item', via: :get
  match '/site/get_shopping_cart_item_info' => 'site#get_shopping_cart_item_info', via: :get
  match '/site/get_cart_summary_body' => 'site#get_cart_summary_body', via: %i[get post put]
  match '/site/get_cart_contents' => 'site#get_cart_contents', via: :get
  match '/site/show_products_with_page' => 'site#show_products_with_page', via: :get
  match '/site/live_product_search' => 'site#live_product_search', via: :get
  match '/site/load_product_style_slider' => 'site#load_product_style_slider', via: :get
  match '/site/retailers' => 'site#retailers', via: :get
  match '/site/product_index_feed' => 'site#product_index_feed', via: :get

  match '/menus/update_checkbox_tag' => 'menus#update_checkbox_tag', via: :post
  match '/menus/render_category_div' => 'menus#render_category_div', via: :get

  # examples of site controller additions
  #  match "/site/show_portfolios" => "site#show_portfolios", via: :get
  #  match "/site/artifact_detail" => "site#artifact_detail", via: :get
end

app/models/product_related_product.rb
# frozen_string_literal: true

class ProductRelatedProduct < ActiveRecord::Base
  belongs_to :product, optional: true
  has_one :related_product, class_name: 'Product',
                            foreign_key: 'id',
                            primary_key: 'related_product_id'

  def self.reorder(id, position)
    puts(id, position)
    ActiveRecord::Base.connection.execute ("UPDATE `product_related_products` SET `position` = '" + position.to_s + "' WHERE `product_related_products`.`id` =" + id.to_s + ' LIMIT 1 ;')
  end
end

app/controllers/product_related_products_controller.rb
# frozen_string_literal: true

class ProductRelatedProductsController < ApplicationController
  before_action :set_product_related_product, only: %i[show edit update destroy]

  # GET /product_related_products
  def index
    @product_related_products = ProductRelatedProduct.all
  end

  # GET /product_related_products/1
  def show; end

  # GET /product_related_products/new
  def new
    @product_related_product = ProductRelatedProduct.new
  end

  # GET /product_related_products/1/edit
  def edit; end

  # POST /product_related_products
  def create
    @product_related_product = ProductRelatedProduct.new(product_related_product_params)

    if @product_related_product.save
      redirect_to @product_related_product, notice: 'Product related product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /product_related_products/1
  def update
    if @product_related_product.update(product_related_product_params)
      redirect_to @product_related_product, notice: 'Product related product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /product_related_products/1
  def destroy
    @product_related_product.destroy
    respond_to do |format|
      format.html { head :ok, notice: 'Product related product was successfully destroyed.' }
      format.json { head :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product_related_product
    @product_related_product = ProductRelatedProduct.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def product_related_product_params
    params.require(:product_related_product).permit(:product_id, :related_prooduct)
  end
end

app/helpers/product_related_products_helper.rb
# frozen_string_literal: true

module ProductRelatedProductsHelper
end

app/views/product_related_products/_form.html.erb
<%= form_for(@product_related_product) do |f| %>
  <% if @product_related_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_related_product.errors.count, "error") %> prohibited this product_related_product from being saved:</h2>

      <ul>
      <% @product_related_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :related_prooduct %><br>
    <%= f.number_field :related_prooduct %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_related_products/edit.html.erb
<h1>Editing Product Related Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_related_product %> |
<%= link_to 'Back', product_related_products_path %>

app/views/product_related_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Related Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Related prooduct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_related_products.each do |product_related_product| %>
      <tr>
        <td><%= product_related_product.product_id %></td>
        <td><%= product_related_product.related_prooduct %></td>
        <td><%= link_to 'Show', product_related_product %></td>
        <td><%= link_to 'Edit', edit_product_related_product_path(product_related_product) %></td>
        <td><%= link_to 'Destroy', product_related_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product related product', new_product_related_product_path %>

app/views/product_related_products/new.html.erb
<h1>New Product Related Product</h1>

<%= render 'form' %>

<%= link_to 'Back', product_related_products_path %>

app/views/product_related_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_related_product.product_id %>
</p>

<p>
  <strong>Related prooduct:</strong>
  <%= @product_related_product.related_prooduct %>
</p>

<%= link_to 'Edit', edit_product_related_product_path(@product_related_product) %> |
<%= link_to 'Back', product_related_products_path %>