config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :product_related_products
  resources :retailers do
    collection do
      get 'create_empty_record'
      get 'delete_ajax'
      post 'retailer_table'
      get 'geocode_addresses'
    end
  end

  get 'secure_site/wholesale_page'

  resources :coupon_usages

  resources :coupons do
    collection do
      get 'create_empty_record'
      post 'coupon_table'
      get 'delete_ajax'
      delete 'delete'
      #  put "index"
      put 'update'
    end
  end

  resources :cart do
    collection do
      post 'update'
    end
  end

  resources :order_items do
    collection do
      get 'create_empty_record'
    end
  end

  resources :orders do
    collection do
      get 'show'
      get 'create_empty_record'
      get 'create_order'
      get 'enter_order'
      post 'enter_order'
      get 'order_success'
      get 'invoice_slip'
      get 'user_orders'
      get 'resend_invoice'
      post 'order_table'
      post 'user_order_table'
      get 'express_purchase'
      get 'product_list_report'
      get 'customer_sales_report'
      get 'invoice_list_report'
      get 'receipt_list_report'
    end
  end

  resources :product_details do
    collection do
      get 'create_empty_record'
      get 'duplicate_record'
      post 'product_details_table'
      get 'delete_ajax'
      delete 'delete'
    end
  end

  resources :suppliers do
    collection do
      get 'create_empty_record'
    end
  end

  resources :products do
    collection do
      get 'create_empty_record'
      post 'product_table'
      get 'show_detail'
      post 'render_category_div'
      get 'render_image_section'
      get 'delete_ajax'
      get 'generate_inventory_report'
      post 'update_checkbox_tag'
      post 'add_image'
      get 'edit_picture'
      get 'edit_picture_swatch'
      post 'update_image_order'
      get 'product_preferences'
      post 'add_image_system'
      get 'reprocess_product_images'
      post 'sort'
      post 'update_related_order'
      get 'product_search'
      post 'update_related_list'
      post 'render_related_section'
      get 'render_swatch_picture'
      get 'clean_product_details'
      get 'activate_all_products'
      get 'clear_product_inventory_and_make_all_inactive'
      get 'hide_inactive_inventory'
      get 'search_fields'
    end
  end

  resources :product_related_products do
    collection do
      delete 'delete'
    end
  end

  match '/site/show_products' => 'site#show_products', via: :get
  match '/site/product_detail' => 'site#product_detail', via: :get
  match '/site/add_to_cart' => 'site#add_to_cart', via: :get
  match '/site/show_cart' => 'site#show_cart', via: :get
  match '/site/empty_cart' => 'site#empty_cart', via: :get
  match '/site/get_sizes_for_color' => 'site#get_sizes_for_color', via: :get
  match '/site/get_shopping_cart_info' => 'site#get_shopping_cart_info', via: :get
  match '/site/check_out' => 'site#check_out', via: :get
  match '/site/cart_update' => 'site#cart_update', via: %i[get put]
  match '/site/increment_cart_item' => 'site#increment_cart_item', via: :get
  match '/site/decrement_cart_item' => 'site#decrement_cart_item', via: :get
  match '/site/delete_cart_item' => 'site#delete_cart_item', via: :get
  match '/site/get_shopping_cart_item_info' => 'site#get_shopping_cart_item_info', via: :get
  match '/site/get_cart_summary_body' => 'site#get_cart_summary_body', via: %i[get post put]
  match '/site/get_cart_contents' => 'site#get_cart_contents', via: :get
  match '/site/show_products_with_page' => 'site#show_products_with_page', via: :get
  match '/site/live_product_search' => 'site#live_product_search', via: :get
  match '/site/load_product_style_slider' => 'site#load_product_style_slider', via: :get
  match '/site/retailers' => 'site#retailers', via: :get
  match '/site/product_index_feed' => 'site#product_index_feed', via: :get

  match '/menus/update_checkbox_tag' => 'menus#update_checkbox_tag', via: :post
  match '/menus/render_category_div' => 'menus#render_category_div', via: :get

  # examples of site controller additions
  #  match "/site/show_portfolios" => "site#show_portfolios", via: :get
  #  match "/site/artifact_detail" => "site#artifact_detail", via: :get
end

app/models/retailer.rb
# frozen_string_literal: true

class Retailer < ActiveRecord::Base
  geocoded_by :address
  before_update :geocode

  def address
    [company_street_1, company_street_2, company_city, company_state, company_zip].compact.join(', ')
   end
end

app/controllers/retailers_controller.rb
# frozen_string_literal: true

class RetailersController < ApplicationController
  # GET /retailers
  # GET /retailers.json
  def index
    @retailers = Retailer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  # GET /retailers/1
  # GET /retailers/1.json
  def show
    @retailer = Retailer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @retailer }
    end
  end

  # GET /retailers/new
  # GET /retailers/new.json
  def new
    @retailer = Retailer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @retailer }
    end
  end

  # GET /retailers/1/edit
  def edit
    @retailer = Retailer.find(params[:id])
  end

  # POST /retailers
  # POST /retailers.json
  def create
    @retailer = Retailer.new(retailer_params)

    respond_to do |format|
      if @retailer.save
        format.html { redirect_to @retailer, notice: 'Retailer was successfully created.' }
        format.json { render json: @retailer, status: :created, location: @retailer }
      else
        format.html { render action: 'new' }
        format.json { render json: @retailer.errors, status: :unprocessable_entry }
      end
    end
  end

  # PUT /retailers/1
  # PUT /retailers/1.json
  def update
    @retailer = Retailer.find(params[:id])

    respond_to do |format|
      if @retailer.update_attributes(retailer_params)
        format.html { redirect_to @retailer, notice: 'Retailer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @retailer.errors, status: 'unprocessable_entry' }
      end
    end
  end

  # DELETE /retailers/1
  # DELETE /retailers/1.json
  def destroy
    @retailer = Retailer.find(params[:id])
    @retailer.destroy

    respond_to do |format|
      format.html { redirect_to retailers_url }
      format.json { head :ok }
    end
  end

  # CREATE_EMPTY_RECORD /retailers/1
  # CREATE_EMPTY_RECORD /retailers/1.json

  def create_empty_record
    @retailer = Retailer.new
    @retailer.company_name = "New Company"
    @retailer.save

    redirect_to(controller: :retailers, action: :edit, id: @retailer)
  end

  def delete_ajax
    @retailer = Retailer.find(params[:id])
    @retailer.destroy
    head :ok
    
  end

  def retailer_table
    @objects = current_objects(params)
    @total_objects = total_objects(params)
    render layout: false
  end

  def geocode_addresses
    Retailer.all.each do |retailer|
      puts("*** *** *** *** ")     
      retailer.geocode
      retailer.save
      puts(retailer.id, retailer.company_state, retailer.latitude, retailer.longitude)

      #      hold =   retailer.company_state
      #      retailer.company_state = ""
      #      retailer.save
      #      puts(retailer.id, retailer.company_state, retailer.latitude, retailer.longitude)
      #      retailer.company_state = hold
      #      retailer.save
      #      puts(retailer.id, retailer.company_state, retailer.latitude, retailer.longitude)
    end
    
    head :ok
  end
  
  private

  def current_objects(params = {})
    current_page = (begin
        params[:start].to_i / params[:length].to_i
      rescue StandardError
        0
      end) + 1
                  
    @current_objects = Retailer.page(current_page).per(params[:length])
    .order("#{datatable_columns(params[:order]['0'][:column])} #{params[:order]['0'][:dir] || 'DESC'}")
    .where(conditions)

    # @current_objects = Retailer.select("retailers.*").
    #   where(conditions).
    #   order("#{datatable_columns(params[:order]["0"][:column])} #{params[:order]["0"][:dir] || "DESC"}")
  end

  def total_objects(_params = {})
    @total_objects = Retailer.where(conditions).count
  end

  def datatable_columns(column_id)
    case column_id.to_i
    when 0
      'retailers.company_name'
    when 1
      'retailers.company_street_1'
    when 2
      'retailers.company_street_2'
    when 3
      'retailers.company_city'
    when 4
      'retailers.company_state'
    when 5
      'retailers.company_zip'
    when 6
      'retailers.company_phone'
    when 7
      'retailers.company_website'
    when 8
      'retailers.company_hours_1'
    when 9
      'retailers.company_hours_2'
    else
      'retailers.company_hours_3'
    end
  end

  def conditions
    conditions = []
    conditions << "(retailers.company_name LIKE '%#{params[:search][:value]}%' OR retailers.company_street_1 LIKE '%#{params[:search][:value]}%' OR retailers.company_street_2 LIKE '%#{params[:search][:value]}%' OR retailers.company_city LIKE '%#{params[:search][:value]}%' OR retailers.company_state LIKE '%#{params[:search][:value]}%' OR retailers.company_zip LIKE '%#{params[:search][:value]}%' OR retailers.company_phone LIKE '%#{params[:search][:value]}%' OR retailers.company_website LIKE '%#{params[:search][:value]}%' OR retailers.company_hours_1 LIKE '%#{params[:search][:value]}%' OR retailers.company_hours_2 LIKE '%#{params[:search][:value]}%' OR retailers.company_hours_3 LIKE '%#{params[:search][:value]}%')" if params[:search][:value]
    conditions.join(' AND ')
  end
  
    
  private
  
  def retailer_params
    params[:retailer].permit(["id", "company_name", "company_street_1", "company_street_2", "company_city", "company_state", "company_zip", "company_phone", "company_website", "company_hours_1", "company_hours_2", "company_hours_3", "latitude", "longitude", "created_at", "updated_at"])
  end
  
   
end

app/helpers/retailers_helper.rb
# frozen_string_literal: true

module RetailersHelper
end

app/views/retailers/_form.html.erb
<div class="cms-content">

    <p>
        <b>Name:</b><br>
        <%=editablefieldcreate("company_name", @retailer)%>
    </p>



    <p>
        <b>Street Address 1</b><br>
        <%=editablefieldcreate("company_street_1", @retailer)%>
    </p>



    <p>
        <b>Street Addres 2</b><br>
        <%=editablefieldcreate("company_street_2", @retailer)%>
    </p>



    <p>
        <b>City</b><br>
        <%=editablefieldcreate("company_city", @retailer)%>
    </p>



    <p>
        <b>State</b><br>
        <%=editablefieldcreate("company_state", @retailer)%>
    </p>



    <p>
        <b>Zip Code</b><br>
        <%=editablefieldcreate("company_zip", @retailer)%>
    </p>


    <p>
        <b>Phone Number</b><br>
        <%=editablefieldcreate("company_phone", @retailer)%>
    </p>


    <p>
        <b>Web Site</b><br>
        <%=editablefieldcreate("company_website", @retailer)%>
    </p>

    <p>
        <b>Company Hours (3 fields)</b><br>
        <%=editablefieldcreate("company_hours_1", @retailer)%></br>
        <%=editablefieldcreate("company_hours_2", @retailer)%></br>
        <%=editablefieldcreate("company_hours_3", @retailer)%></br>
    </p>

</div>

app/views/retailers/edit.html.erb
<div class="hidden-item">
    <div id="as_window"><%=params[:request_type]=="window"%></div>
    <div id="dialog-height">650</div>
    <div id="dialog-width">1050</div>
    <div id="dialog-name">Edit Retailer(<%=@retailer.id.to_s%>)</div>
</div>


<div class="myaccountblock" Align="Left">
    <div align="center">
    <!-- START:flash -->
    <% if notice -%>
      <div id="notice"><%= notice  %></div>
    <% end -%>
    <!-- END:flash -->
    
    <% if @retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
      <% @retailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  </div>

    <div class="myaccountcontent">

      <%= render 'form' %>

         </div>
</div>

app/views/retailers/index.html.erb
<div class="hidden-item">
    <div id="as_window"><%=params[:request_type]=="window"%></div>
    <div id="dialog-height">650</div>
    <div id="dialog-width">1050</div>
    <div id="dialog-name">Retailers</div>
</div>

<div class="myaccountblock">
  <div align="center">
    <!-- START:flash -->
    <% if flash[:notice] -%>
      <div id="notice"><%= flash[:notice] %></div>
    <% end -%>
    <!-- END:flash -->
  </div>

  <div id="site-pref-list">
    <p>
    <center><%= link_to 'New Retailer', {:action=>:create_empty_record,:typeofrecord=>"Retailer"}, :class=>"button-link", :id=>"new-retailer", :remote=>true%>
         <%= link_to 'Geocode Addresses', {:action=>:geocode_addresses,:typeofrecord=>"Retailer"}, :class=>"button-link", :id=>"geocode-addresses", :remote=>true%></center>
</br>
</p>
        <table cellpadding="0" cellspacing="0" border="0" class="display" id="retailer-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
          <th>-</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
      <tfoot>
        <tr>
        <th>Name</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
          <th>-</th>
        </tr>
      </tfoot>
    </table>
</div>

app/views/retailers/index.json.erb
[
 <% @retailers.each do |retailer| %>
  {
  "id":"<%= retailer.id%>",
  "name":"<%= retailer.company_name.html_safe%>",
  "lat":"<%= retailer.latitude%>",
  "lng":"<%= retailer.longitude%>",
  "address":"<%= retailer.company_street_1%>",
  "address2":"<%= retailer.company_street_2%>",
  "city":"<%= retailer.company_city%>",
  "state":"<%= retailer.company_state%>",
  "postal":"<%= retailer.company_zip%>",
  "phone":"<%= retailer.company_phone%>",
  "web":"<%= retailer.company_website%>",
  "hours1":"<%= retailer.company_hours_1%>",
  "hours2":"<%= retailer.company_hours_2%>",
  "hours3":"<%= retailer.company_hours_3%>"
  }
  <% if @retailers.last != retailer then %> , <% end %>
<% end %>
]

app/views/retailers/new.html.erb
<div class="myaccountblock" Align="Left">
    <div align="center">
    <!-- START:flash -->
    <% if notice -%>
      <div id="notice"><%= notice  %></div>
    <% end -%>
    <!-- END:flash -->
    
   <% if @retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
      <% @retailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div class="myaccountheader">New Retailer</div>
  <div class="myaccountsection">
    <div class="myaccountheading">Information for retailer</div>
    <div class="myaccountcontent">

      <%= render 'form' %>

         </div>
    </p>
  </div>
  
<%= link_to 'Show', @retailer %> |
<%= link_to 'Back', retailers_path %>
   

</div>

app/views/retailers/retailer_table.json.erb
{"draw": <%= params[:draw] || -1 %>,
 "recordsTotal": <%= @total_objects %>,
 "recordsFiltered": <%= @total_objects %>,
 "data":[
<% @objects.each do |retailer| %>
  [
   "<%=editablefieldcreate('company_name', retailer,"name").gsub("\"", "'").html_safe() %> <div id='retailer-id' class='hidden-item'> <%= retailer.id%></div> ",
   "<%=editablefieldcreate('company_street_1', retailer,"name").gsub("\"", "'").html_safe() %>",
   "<%=editablefieldcreate('company_city', retailer,"name").gsub("\"", "'").html_safe() %>",
   "<%=editablefieldcreate('company_state', retailer,"name").gsub("\"", "'").html_safe() %>",
   "<%=editablefieldcreate('company_zip', retailer,"name").gsub("\"", "'").html_safe() %>",
   "<center><div class='delete-retail-item'><%=image_tag('interface/delete.png', :border=>'0').gsub("\"", "'").html_safe() %></div> </center>"
] <% if @objects.last != retailer then %> , <% end %>
<% end %>
]}

app/views/retailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @retailer.company_name %>
</p>

<p>
  <b>Company street 1:</b>
  <%= @retailer.company_street_1 %>
</p>

<p>
  <b>Company street 2:</b>
  <%= @retailer.company_street_2 %>
</p>

<p>
  <b>Company city:</b>
  <%= @retailer.company_city %>
</p>

<p>
  <b>Company state:</b>
  <%= @retailer.company_state %>
</p>

<p>
  <b>Company zip:</b>
  <%= @retailer.company_zip %>
</p>

<p>
  <b>Company zip:</b>
  <%= @retailer.company_phone %>
</p>

<p>
  <b>Company zip:</b>
  <%= @retailer.company_website %>
</p>


<p>
  <b>Hours (3 fields):</b>
  <%= @retailer.company_hours_1 %></br>
  <%= @retailer.company_hours_2 %></br>
  <%= @retailer.company_hours_3 %></br>
  
</p>


<%= link_to 'Edit', edit_retailer_path(@retailer) %> |
<%= link_to 'Back', retailers_path %>