config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :product_related_products
  resources :retailers do
    collection do
      get 'create_empty_record'
      get 'delete_ajax'
      post 'retailer_table'
      get 'geocode_addresses'
    end
  end

  get 'secure_site/wholesale_page'

  resources :coupon_usages

  resources :coupons do
    collection do
      get 'create_empty_record'
      post 'coupon_table'
      get 'delete_ajax'
      delete 'delete'
      #  put "index"
      put 'update'
    end
  end

  resources :cart do
    collection do
      post 'update'
    end
  end

  resources :order_items do
    collection do
      get 'create_empty_record'
    end
  end

  resources :orders do
    collection do
      get 'show'
      get 'create_empty_record'
      get 'create_order'
      get 'enter_order'
      post 'enter_order'
      get 'order_success'
      get 'invoice_slip'
      get 'user_orders'
      get 'resend_invoice'
      post 'order_table'
      post 'user_order_table'
      get 'express_purchase'
      get 'product_list_report'
      get 'customer_sales_report'
      get 'invoice_list_report'
      get 'receipt_list_report'
    end
  end

  resources :product_details do
    collection do
      get 'create_empty_record'
      get 'duplicate_record'
      post 'product_details_table'
      get 'delete_ajax'
      delete 'delete'
    end
  end

  resources :suppliers do
    collection do
      get 'create_empty_record'
    end
  end

  resources :products do
    collection do
      get 'create_empty_record'
      post 'product_table'
      get 'show_detail'
      post 'render_category_div'
      get 'render_image_section'
      get 'delete_ajax'
      get 'generate_inventory_report'
      post 'update_checkbox_tag'
      post 'add_image'
      get 'edit_picture'
      get 'edit_picture_swatch'
      post 'update_image_order'
      get 'product_preferences'
      post 'add_image_system'
      get 'reprocess_product_images'
      post 'sort'
      post 'update_related_order'
      get 'product_search'
      post 'update_related_list'
      post 'render_related_section'
      get 'render_swatch_picture'
      get 'clean_product_details'
      get 'activate_all_products'
      get 'clear_product_inventory_and_make_all_inactive'
      get 'hide_inactive_inventory'
      get 'search_fields'
    end
  end

  resources :product_related_products do
    collection do
      delete 'delete'
    end
  end

  match '/site/show_products' => 'site#show_products', via: :get
  match '/site/product_detail' => 'site#product_detail', via: :get
  match '/site/add_to_cart' => 'site#add_to_cart', via: :get
  match '/site/show_cart' => 'site#show_cart', via: :get
  match '/site/empty_cart' => 'site#empty_cart', via: :get
  match '/site/get_sizes_for_color' => 'site#get_sizes_for_color', via: :get
  match '/site/get_shopping_cart_info' => 'site#get_shopping_cart_info', via: :get
  match '/site/check_out' => 'site#check_out', via: :get
  match '/site/cart_update' => 'site#cart_update', via: %i[get put]
  match '/site/increment_cart_item' => 'site#increment_cart_item', via: :get
  match '/site/decrement_cart_item' => 'site#decrement_cart_item', via: :get
  match '/site/delete_cart_item' => 'site#delete_cart_item', via: :get
  match '/site/get_shopping_cart_item_info' => 'site#get_shopping_cart_item_info', via: :get
  match '/site/get_cart_summary_body' => 'site#get_cart_summary_body', via: %i[get post put]
  match '/site/get_cart_contents' => 'site#get_cart_contents', via: :get
  match '/site/show_products_with_page' => 'site#show_products_with_page', via: :get
  match '/site/live_product_search' => 'site#live_product_search', via: :get
  match '/site/load_product_style_slider' => 'site#load_product_style_slider', via: :get
  match '/site/retailers' => 'site#retailers', via: :get
  match '/site/product_index_feed' => 'site#product_index_feed', via: :get

  match '/menus/update_checkbox_tag' => 'menus#update_checkbox_tag', via: :post
  match '/menus/render_category_div' => 'menus#render_category_div', via: :get

  # examples of site controller additions
  #  match "/site/show_portfolios" => "site#show_portfolios", via: :get
  #  match "/site/artifact_detail" => "site#artifact_detail", via: :get
end

app/models/coupon_usage.rb
# frozen_string_literal: true

class CouponUsage < ActiveRecord::Base
  belongs_to :user, optional: true
  belongs_to :coupon, optional: true
end

app/controllers/coupon_usages_controller.rb
# frozen_string_literal: true

class CouponUsagesController < ApplicationController
  # GET /coupon_usages
  # GET /coupon_usages.json
  def index
    @coupon_usages = CouponUsage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coupon_usages }
    end
  end

  # GET /coupon_usages/1
  # GET /coupon_usages/1.json
  def show
    @coupon_usage = CouponUsage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coupon_usage }
    end
  end

  # GET /coupon_usages/new
  # GET /coupon_usages/new.json
  def new
    @coupon_usage = CouponUsage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coupon_usage }
    end
  end

  # GET /coupon_usages/1/edit
  def edit
    @coupon_usage = CouponUsage.find(params[:id])
  end

  # POST /coupon_usages
  # POST /coupon_usages.json
  def create
    @coupon_usage = CouponUsage.new(params[:coupon_usage])

    respond_to do |format|
      if @coupon_usage.save
        format.html { redirect_to @coupon_usage, notice: 'Coupon usage was successfully created.' }
        format.json { render json: @coupon_usage, status: :created, location: @coupon_usage }
      else
        format.html { render action: 'new' }
        format.json { render json: @coupon_usage.errors, status: :unprocessable_entry }
      end
    end
  end

  # PUT /coupon_usages/1
  # PUT /coupon_usages/1.json
  def update
    @coupon_usage = CouponUsage.find(params[:id])

    respond_to do |format|
      if @coupon_usage.update_attributes(params[:coupon_usage])
        format.html { redirect_to @coupon_usage, notice: 'Coupon usage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coupon_usage.errors, status: 'unprocessable_entry' }
      end
    end
  end

  # DELETE /coupon_usages/1
  # DELETE /coupon_usages/1.json
  def destroy
    @coupon_usage = CouponUsage.find(params[:id])
    @coupon_usage.destroy

    respond_to do |format|
      format.html { redirect_to coupon_usages_url }
      format.json { head :ok }
    end
  end

  # CREATE_EMPTY_RECORD /coupon_usages/1
  # CREATE_EMPTY_RECORD /coupon_usages/1.json

  def create_empty_record
    @coupon_usage = CouponUsage.new
    @coupon_usage.save

    redirect_to(controller: :coupon_usages, action: :edit, id: @coupon_usage)
  end
end

app/helpers/coupon_usages_helper.rb
# frozen_string_literal: true

module CouponUsagesHelper
end

app/views/coupon_usages/_form.html.erb
      <p>
        <b>coupon_id:</b><br>
        <%=editablefieldcreate("coupon_id", @coupon_usage)%>
      </p>



      <p>
        <b>user_id:</b><br>
        <%=editablefieldcreate("user_id", @coupon_usage)%>
      </p>



      <p>
        <b>usage_count:</b><br>
        <%=editablefieldcreate("usage_count", @coupon_usage)%>
      </p>


      

app/views/coupon_usages/edit.html.erb
<div class="myaccountblock" Align="Left">
    <div align="center">
    <!-- START:flash -->
    <% if notice -%>
      <div id="notice"><%= notice  %></div>
    <% end -%>
    <!-- END:flash -->
    
    <% if @coupon_usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon_usage.errors.count, "error") %> prohibited this coupon_usage from being saved:</h2>

      <ul>
      <% @coupon_usage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  </div>

  <div class="myaccountheader">Edit Coupon usage</div>
  <div class="myaccountsection">
    <div class="myaccountheading">Information for coupon_usage</div>
    <div class="myaccountcontent">

      <%= render 'form' %>

         </div>
    </p>
  </div>
  
<%= link_to 'Show', @coupon_usage %> |
<%= link_to 'Back', coupon_usages_path %>
   

</div>

app/views/coupon_usages/index.html.erb
<div class="myaccountblock">
  <div align="center">
    <!-- START:flash -->
    <% if flash[:notice] -%>
      <div id="notice"><%= flash[:notice] %></div>
    <% end -%>
    <!-- END:flash -->
  </div>

  <div id="site-pref-list">
    <h1  class="myaccountheader">Coupon usage</h1>

    <center><%= link_to 'New Coupon usage', :action=>:create_empty_record,:typeofrecord=>"coupon_usage" %></center>

    <%  @coupon_usages.each do |coupon_usage| %>
      <div class="hr"></div>
      <table width ="100%"cellpadding="5" cellspacing="0">
        <tr class="list-table" valign="top" class="<%= cycle('list-line-odd', 'list-line-even') %>"  onclick = "window.location.href ='<%=url_for(:controller => 'coupon_usages', :id => coupon_usage.id,  :action => 'edit')%>' "  style = "cursor:pointer" >
                      <td align="left">
    <span class="list-title"><%= coupon_usage.coupon_id %></span>
          </td>
                   <td align="left">
    <span class="list-title"><%= coupon_usage.user_id %></span>
          </td>
                   <td align="left">
    <span class="list-title"><%= coupon_usage.usage_count %></span>
          </td>
          
        </tr>
      </table>
      <div align="right" class="image-delete-list" >
        <%=link_to image_tag ("Button-Delete.png", :border=>"0") , coupon_usage,:on_click=>"", :confirm => 'Are you sure?', :method => :delete %>
      </div>
    <% end %>
    <div class="hr"></div>

  </div>
    <center><%= link_to 'New Coupon usage', :action=>:create_empty_record,:typeofrecord=>"coupon_usage" %></center>
</div>

app/views/coupon_usages/new.html.erb
<div class="myaccountblock" Align="Left">
    <div align="center">
    <!-- START:flash -->
    <% if notice -%>
      <div id="notice"><%= notice  %></div>
    <% end -%>
    <!-- END:flash -->
    
   <% if @coupon_usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon_usage.errors.count, "error") %> prohibited this coupon_usage from being saved:</h2>

      <ul>
      <% @coupon_usage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div class="myaccountheader">New Coupon usage</div>
  <div class="myaccountsection">
    <div class="myaccountheading">Information for coupon_usage</div>
    <div class="myaccountcontent">

      <%= render 'form' %>

         </div>
    </p>
  </div>
  
<%= link_to 'Show', @coupon_usage %> |
<%= link_to 'Back', coupon_usages_path %>
   

</div>

app/views/coupon_usages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Coupon:</b>
  <%= @coupon_usage.coupon_id %>
</p>

<p>
  <b>User:</b>
  <%= @coupon_usage.user_id %>
</p>

<p>
  <b>Usage count:</b>
  <%= @coupon_usage.usage_count %>
</p>


<%= link_to 'Edit', edit_coupon_usage_path(@coupon_usage) %> |
<%= link_to 'Back', coupon_usages_path %>