config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :product_related_products
  resources :retailers do
    collection do
      get 'create_empty_record'
      get 'delete_ajax'
      post 'retailer_table'
      get 'geocode_addresses'
    end
  end

  get 'secure_site/wholesale_page'

  resources :coupon_usages

  resources :coupons do
    collection do
      get 'create_empty_record'
      post 'coupon_table'
      get 'delete_ajax'
      delete 'delete'
      #  put "index"
      put 'update'
    end
  end

  resources :cart do
    collection do
      post 'update'
    end
  end

  resources :order_items do
    collection do
      get 'create_empty_record'
    end
  end

  resources :orders do
    collection do
      get 'show'
      get 'create_empty_record'
      get 'create_order'
      get 'enter_order'
      post 'enter_order'
      get 'order_success'
      get 'invoice_slip'
      get 'user_orders'
      get 'resend_invoice'
      post 'order_table'
      post 'user_order_table'
      get 'express_purchase'
      get 'product_list_report'
      get 'customer_sales_report'
      get 'invoice_list_report'
      get 'receipt_list_report'
    end
  end

  resources :product_details do
    collection do
      get 'create_empty_record'
      get 'duplicate_record'
      post 'product_details_table'
      get 'delete_ajax'
      delete 'delete'
    end
  end

  resources :suppliers do
    collection do
      get 'create_empty_record'
    end
  end

  resources :products do
    collection do
      get 'create_empty_record'
      post 'product_table'
      get 'show_detail'
      post 'render_category_div'
      get 'render_image_section'
      get 'delete_ajax'
      get 'generate_inventory_report'
      post 'update_checkbox_tag'
      post 'add_image'
      get 'edit_picture'
      get 'edit_picture_swatch'
      post 'update_image_order'
      get 'product_preferences'
      post 'add_image_system'
      get 'reprocess_product_images'
      post 'sort'
      post 'update_related_order'
      get 'product_search'
      post 'update_related_list'
      post 'render_related_section'
      get 'render_swatch_picture'
      get 'clean_product_details'
      get 'activate_all_products'
      get 'clear_product_inventory_and_make_all_inactive'
      get 'hide_inactive_inventory'
      get 'search_fields'
    end
  end

  resources :product_related_products do
    collection do
      delete 'delete'
    end
  end

  match '/site/show_products' => 'site#show_products', via: :get
  match '/site/product_detail' => 'site#product_detail', via: :get
  match '/site/add_to_cart' => 'site#add_to_cart', via: :get
  match '/site/show_cart' => 'site#show_cart', via: :get
  match '/site/empty_cart' => 'site#empty_cart', via: :get
  match '/site/get_sizes_for_color' => 'site#get_sizes_for_color', via: :get
  match '/site/get_shopping_cart_info' => 'site#get_shopping_cart_info', via: :get
  match '/site/check_out' => 'site#check_out', via: :get
  match '/site/cart_update' => 'site#cart_update', via: %i[get put]
  match '/site/increment_cart_item' => 'site#increment_cart_item', via: :get
  match '/site/decrement_cart_item' => 'site#decrement_cart_item', via: :get
  match '/site/delete_cart_item' => 'site#delete_cart_item', via: :get
  match '/site/get_shopping_cart_item_info' => 'site#get_shopping_cart_item_info', via: :get
  match '/site/get_cart_summary_body' => 'site#get_cart_summary_body', via: %i[get post put]
  match '/site/get_cart_contents' => 'site#get_cart_contents', via: :get
  match '/site/show_products_with_page' => 'site#show_products_with_page', via: :get
  match '/site/live_product_search' => 'site#live_product_search', via: :get
  match '/site/load_product_style_slider' => 'site#load_product_style_slider', via: :get
  match '/site/retailers' => 'site#retailers', via: :get
  match '/site/product_index_feed' => 'site#product_index_feed', via: :get

  match '/menus/update_checkbox_tag' => 'menus#update_checkbox_tag', via: :post
  match '/menus/render_category_div' => 'menus#render_category_div', via: :get

  # examples of site controller additions
  #  match "/site/show_portfolios" => "site#show_portfolios", via: :get
  #  match "/site/artifact_detail" => "site#artifact_detail", via: :get
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  #  uses_tiny_mce( options: AppConfig.full_mce_options.merge({width: "897px"}),  only: [:new, :edit],
  #    raw_options: "template_templates : [ {
  #                                                        title : 'Editor Details',
  #                                                        src : 'editor_details.htm',
  #                                                        description : 'Adds Editors Name and Staff ID'
  #                                                    } ]#"
  #
  #
  #  )

  # GET /products
  # GET /products.json
  def index
    session[:mainnav_status] = true

    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    session[:mainnav_status] = true

    @product = Product.find(params[:id])
    @colors =  @product.product_details.select('distinct `color`').pluck(:color)
    @image_locations = ['Slider', 'Primary', 'Product List', '-']
    @product_layouts = [['Normal', ''], %w[Horizontal horizontal]]

    @sizes = begin
      Settings.inventory_size_list.split(',').collect { |x| x } || ''.dup
    rescue StandardError
      []
    end
    @system_colors = SystemImages.swatches.pluck(:title)
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entry }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    preferences_update = false

    if (params[:id] == 'product_preferences') || (params[:id] == 'settings')
      params_settings = settings_params

      if params_settings.to_h.keys[0] == 'category_group'
        category_list = Settings.category_group.to_s
        category = params_settings.to_h.values[0]
        if category_list.include?(category)
          new_cat_list = category_list.to_s.split(',').reject { |elem| elem == category }.join(',')
        else
          new_cat_list = (category_list.to_s.split(',') << category).join(',')
        end
        Settings.category_group = new_cat_list
      else
        eval("Settings.#{params_settings.to_h.keys[0]}=\"#{params_settings.to_h.values[0].to_s.html_safe}\"")
      end

      preferences_update = true
    else

      @product = Product.find(params[:id])
      successfull = @product.update_attributes(product_params)
    end

    respond_to do |format|
      if preferences_update
        format.html { render nothing: true }
        format.json { render json: { notice: 'Preferences were successfully updated.' } }

      else
        if successfull
          format.html { redirect_to action: 'edit', notice: 'Product was successfully updated.' }
          format.json { render json: { notice: 'Product was successfully updated.' } }
        else
          format.html { render action: 'edit' }
          format.json { render json: @product.errors, status: 'unprocessable_entry' }
        end
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end

  # CREATE_EMPTY_RECORD /products/1
  # CREATE_EMPTY_RECORD /products/1.json

  def create_empty_record
    @product = Product.new
    @product.product_name = 'New Product'
    @product.product_description = 'Edit Me.'
    @product.unit_price = 0
    @product.msrp = 0
    respond_to do |format|
      if @product.save then
        format.html { redirect_to action: 'edit', id: @product.id }
        format.json { render json: { notice: 'Product was successfully created.' } }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: 'unprocessable_entry' }
      end
    end
  end

  def show_detail
    @product = Product.find(params[:id])
    @sizes = begin
      Settings.inventory_size_list.split(',').collect { |x| x } || []
    rescue StandardError
      []
    end
    @system_colors = SystemImages.swatches.pluck(:title)

    render partial: 'detail_list'
  end

  def product_table
    @objects = current_objects(params)
    @total_objects = total_objects(params)
    render layout: false
  end

  def add_image
    @product = Product.find(params[:id])
    @colors =  @product.product_details.select('distinct `color`').pluck(:color)
    @image_locations = ['Slider', 'Primary', 'Product List', '-']

    format = params[:format]
    image = params[:image]

    unless image.blank?
      @picture = Picture.new(image: image)
      @picture.position = 999
      @picture.active_flag = true
      image_saved = @picture.save
      @product.pictures << @picture
    end

    puts("@picture -----____----#{@picture.inspect}")
    puts("image_saved -----____----#{image_saved}")

    respond_to do |format|
      if image_saved
        #    format.js   { render action: '../pictures/create.js' }
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entry }
      end
    end
  end

  def add_image_system
    format = params[:format]

    @picture = SystemImages.new(params[:image_name], params[:image])
    @picture.resource_type = 'Swatch'

    (image_saved = !@picture.blank?) && @picture.save

    puts("@picture -----____----#{@picture.inspect}")
    puts("image_saved -----____----#{image_saved}")

    respond_to do |format|
      if image_saved
        format.js   { render action: '../pictures/create.js' }
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entry }
      end
    end
  end

  def delete_image
    @product = Product.find(params[:incoming_id])
    @image = Picture.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.js if request.xhr?
      format.html { redirect_to action: 'show', id: params[:menu_id] }
    end
  end

  def destroy_image
    @image = Picture.find(params[:id])
    @image.destroy
    redirect_to action: 'show', id: params[:menu_id]
  end

  def update_image_order
    params[:picture].each_with_index do |id, position|
      #   Image.update(id, :position => position)
      Picture.reorder(id, position)
    end
    head :ok
  end

  def update_related_order
    params[:related].each_with_index do |id, position|
      #     related_product = ProductRelatedProduct.find(id)
      #     related_product.position = position
      #     related_product.save
      #   Image.update(id, :position => position)
      ProductRelatedProduct.reorder(id, position)
    end
    head :ok

  end

  def edit_picture
    @picture = Picture.find(params[:picture_id])
    @image_locations = ['Slider', 'Primary', 'Product List', '-']
    @product = Product.find(@picture.resource_id)
    @colors =  @product.product_details.select('distinct `color`').pluck(:color)
    @image_locations += @colors

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @picture }
    end
  end

  def edit_picture_swatch
    @picture = Picture.find(params[:picture_id])
    @image_locations = ['Slider', 'Primary', 'Product List', '-']

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @picture }
    end
  end

  def update_checkbox_tag
    @product = Product.find(params[:id])
    @tag_name = params[:tag_name] || 'tag_list'
    # truely toggle the value

    if @product.send(@tag_name).include?(params[:field])
      @product.send(@tag_name).remove(params[:field])
    else
      @product.send(@tag_name).add(params[:field])
    end

    #    if params[:current_status]== "false" then
    #      @product.send(@tag_name).remove(params[:field])
    #    else
    #      @product.send(@tag_name).add(params[:field])
    #    end
    @product.save

    head :ok

    #   respond_to do |format|
    #       format.js if request.xhr?
    #       format.html {redirect_to :action => 'show', :id=>params[:id]}
    #  end
  end

  def render_category_div
    @product = Product.find(params[:id])
    render(partial: 'category_div')
  end

  def render_swatch_picture
    class_name = params[:class_name]

    @picture = Picture.where(id: params[:id]).first
    if class_name.blank?
      render partial: '/products/swatch_view.html'
    else
      render partial: class_name.downcase + 's' + '/swatch_view.html'
    end
  end

  def render_image_section
    @product = Product.find(params[:id])
    @colors = @product.product_details.select('distinct `color`').pluck(:color)
    @image_locations = ['Slider', 'Primary', 'Product List', '-']

    render(partial: 'image_section')
  end

  def render_related_section

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def create_group_checks_live(_field_name, field_pointer, value_list, tag_list_name, html_options = {})
    return_value = ''.dup

    value_list.each do |item|
      return_value = return_value + "<div class='div-#{tag_list_name}'>" + editablecheckboxtag2(item, field_pointer, item, tag_list_name, html_options) + '</div>'
    end
    return_value.html_safe
  end

  def product_info(product)
    returnval = '<div id="attr-products" class="hidden-item">'.dup
    returnval << '<div id="product-id">' + (begin
                                              product.id.to_s
                                            rescue StandardError
                                              '-1'
                                            end) + '</div>'

    returnval += '</div>'
    returnval.html_safe
  end

  def main_image_preview(picture)
    thumb_picture = picture.file_type == '.pdf' ? image_tag(picture.image_url(:pdf_thumb).to_s) : image_tag(picture.image_url(:thumb).to_s)
    preview_picture = picture.file_type == '.pdf' ? picture.image_url(:pdf_preview).to_s : picture.image_url(:large).to_s

    begin
      return(link_to(thumb_picture, preview_picture, class: 'zoom-image').gsub(/\\|"/) { |c| "\\#{c}" }.html_safe)
    rescue StandardError
      ''
    end
  rescue StandardError
    ''
  end

  def product_edit_div(product)
    returnval = ''.dup
    if session[:user_id]
      user = User.find(session[:user_id])
      if user.roles.detect { |role| ((role.name == 'Admin') | (role.name == 'Site Owner')) }
        returnval = '<div id="edit-product" class="edit-product">'.dup
        returnval << "<div id='product-id' class='hidden-item'>#{product.id}</div>"
        returnval += image_tag('interface/edit.png', border: '0', class: 'imagebutton', title: 'Edit this Product')
        returnval += '</div>'

      end
    end
    returnval.html_safe
  end

  def get_share_code_product
    if !Settings.product_javascript_social_share.blank?
      (CGI.unescapeHTML(Settings.product_javascript_social_share) + CGI.unescapeHTML(Settings.product_button_block_social_share)).html_safe
      #+ Settings.blog_button_block_social_share.html_safe
    else
      ''
    end
  end
end

app/views/products/_detail_list.html.erb
<table  cellpadding="0" cellspacing="0" border="0" class="display" id="product-detail-list-table">
  <thead>
    <tr>
      <th>Avlbl</th>
      <th>Inventory Key</th>
      <th><%= sizelabel(@product)%></th>
      <th>Color</th>
      <th>In Stock</th>
      <th>On Order</th>
      <th>-</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  <tfoot>
    <tr>
      <th>Avlbl</th>
      <th>Inventory Key</th>
      <th><%=sizelabel(@product)%></th>
      <th>Color</th>
      <th>In Stock</th>
      <th>On Order</th>
      <th>-</th>
    </tr>
  </tfoot>
</table>

app/views/products/_form.html.erb
<div class="hidden-item" id="current-product-id"><%= @product.id %></div>

<div id="product-info-div">

  <fieldset class="product-legend" >

    <legend class="address-lable">Product Information:</legend>


    <table  class="address-table">
      <tr>
        <td>
          Product Active: <%=editablecheckboxedit("product_active", @product, "Available?")%>

        </td>
      </tr>
      <tr>
        <td>
          Product Name: <%=editablefieldcreate("product_name", @product)%>
        </td>
      </tr>
      
      <tr>
        <td>
          Search Terms: <%=editablefieldcreate("search_terms", @product)%>
        </td>
      </tr>
      <tr>
        <td>
          Product Description:<br>
          
          <%=form_for(@product, :remote=>true, :id=>"product_description", :format=>:json) do |f| %>
              <%= f.submit "Update", :class=>"hidden-item"%><br>

              <center>
                  <%= f.text_area :product_description, :class => "tinymce-product" , :rows => "80", :cols => "120" %>
                  <%= tinymce_settings(:default,"tinymce_config",{mode: "exact", selector: "textarea.tinymce-product", save_onsavecallback: "mysave", height: "375", width: "950"})%>   
              </center>
              <br>
            <% end %>
        </td>
      </tr>
    </table>
  </fieldset>
</div>

<div class="clear"></div>

<div id="product-vendor-info">
  <fieldset class="address-legend" >
    <legend class="address-lable">Tracking</legend>
    <table  class="address-table">
      <tbody>
        <tr>
          <%#*<td>%>
            <%#*ID: </br> <%=editablefieldcreate("product_id", @product)% >%>
          <%#*</td>%>
          <td>
            Style Number:</br> <%=editablefieldcreate("supplier_product_id", @product)%>
          </td>
          <td>
            Vendor Name:</br>  <%=editablefieldcreate("sheet_name", @product)%>
          </td>
        </tr>

        <tr>
          <%#*<td>Quantity Per Unit:</br><%=editablefieldcreate("quantity_per_unit", @product)% ></td>%>
          <%#*<td>Unit Size:</br> <%=editablefieldcreate("unit_size", @product)% ></td>%>
          <td></td>
          <td>Is Taxable: <%=editablecheckboxedit("is_taxable", @product, "Sales Tax Applies?")%></td>
        </tr>
        <tr>
          <td>
            Reorder Level: <%=editablefieldcreate("reorder_level", @product)%>
          </td>
          <%#*<td>%>
          <%#*</td>%>

          <td>
            Ranking:   <%=editablefieldcreate("product_ranking", @product)%></br>
            Sort Order:   <%=editablefieldcreate("position", @product)%>

          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
</div>



<div id="product-pricing">
  <fieldset class="address-legend" >
    <legend class="address-lable">Pricing</legend>
    <table  class="address-table">
      <tbody>
        <tr>
          <td>
            Cost: </br>   <%=editablefieldcreate("unit_price", @product)%>
          </td>
          <td>
            MSRP: </br> <%=editablefieldcreate("msrp", @product)%>
          </td>
        </tr>
        <tr>
          <td>
            Discount: </br> <%=editablecheckboxedit("discount_available", @product, "Available?")%> <%=editablefieldcreate("discount", @product)%>   
          </td>
           <td>
            No Coupon Applies: </br> <%=editablecheckboxedit("no_coupon", @product, "No Coupon?")%>   
          </td>
        </tr>
        <tr>
            <td span="2">
                        <td>Use Size as varaible price <%=editablecheckboxedit("use_size_as_price", @product, "Use Size as Price?")%></td>

            </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
</div>


<div id="product-classification">
  <fieldset class="address-legend" >
    <legend class="address-lable">Classification</legend>
    <table  class="address-table">
      <tbody>
        <tr>
          <td>

            Department: </br>
            <%#=ajax_select2("department_id","product",@product, create_menu_list("Top Menu"))%>            
            <%=create_group_checks_live("department_id", @product, create_menu_list("Top Menu",false),"department",{:class=>"department-check"} )%>

          </td>
        </tr>
        <tr>
          <td>
            Category: </br>             
            <div id="category-div">
              <%=render(:partial=>"category_div")%>  
            </div>
          

<%#=create_group_checks_live("category_id", @product, create_menu_list("Top Menu"),"category" )%>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
</div>


<%#*<p>%>
<%#*<b>product_id:</b><br>%>
<%#=editablefieldcreate("product_id", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>sku:</b><br>%>
<%#=editablefieldcreate("sku", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>supplier_product_id:</b><br>%>
<%#=editablefieldcreate("supplier_product_id", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>product_name:</b><br>%>
<%#=editablefieldcreate("product_name", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>product_description:</b><br>%>
<%#=editablefieldcreate("product_description", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>supplier_id:</b><br>%>
<%#=editablefieldcreate("supplier_id", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>department_id:</b><br>%>
<%#=editablefieldcreate("department_id", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>category_id:</b><br>%>
<%#=editablefieldcreate("category_id", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>quantity_per_unit:</b><br>%>
<%#=editablefieldcreate("quantity_per_unit", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>unit_size:</b><br>%>
<%#=editablefieldcreate("unit_size", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>unit_price:</b><br>%>
<%#=editablefieldcreate("unit_price", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>msrp:</b><br>%>
<%#=editablefieldcreate("msrp", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>product_detail_id:</b><br>%>
<%#=editablefieldcreate("product_detail_id", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>discount:</b><br>%>
<%#=editablefieldcreate("discount", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>unit_weight:</b><br>%>
<%#=editablefieldcreate("unit_weight", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>reorder_level:</b><br>%>
<%#=editablefieldcreate("reorder_level", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>product_active:</b><br>%>
<%#=editablefieldcreate("product_active", @product)%>

<%#*</p>%>



<%#*<p>%>
<%#*<b>discount_available:</b><br>%>
<%#=editablefieldcreate("discount_available", @product)%>
<%#*</p>%>



<%#*<p>%>
<%#*<b>product_ranking:</b><br>%>
<%#=editablefieldcreate("product_ranking", @product)%>
<%#*</p>%>

app/views/products/_image.html.erb
<div id="image_<%= image.id%>" data-id='image_<%=image.id.to_s%>' class="imageSingle">
  <div class="imageThumb">
    <%= image_tag(image.image_url(:large).to_s) %>
  </div>
  <div class="imageName">
    <%@image=image%>
    Location     <%#=editablefieldcreate("title", image)%> <br>
     <%=ajax_select2("title","image",@image,(@image_locations + ["n/a"]+[image.title]).uniq)%> <br>
    <%=editablecheckboxedit("active_flag", @image, "Visible")%>
  </div>
   <div class="imageDelete">
   <%=link_to(image_tag("interface/Button-Delete.png"), {:id=>image, :incoming_id=>params[:id], :action=>"delete_image", :format=>"js"}, :class=>"delete_image", :confirm => 'Are you sure?', :remote=>true) %> 
   
   </div>
</div>

app/views/products/_image_swatch_section.html.erb
<div class="imagesection">
    <!-- START:hidden_div -->

    <div class="<%= (@all_pictures.count > 999 ? 'hidden-item' : '')%>" id="imagebutton" >              
        <%= render(:partial => "/pictures/upload_button_multi") %>
    </div>

    <div class="<%= (@all_pictures.empty? ? 'hidden-item' : '')%>" id="images" >              
        <%= render(:partial => "swatch_list", :object => @all_pictures) %>
    </div>


    <%= render(:partial=>"/pictures/upload_template") %>

</div> 

app/views/products/_layout_info.html.erb
<div id="product-classification">
  <fieldset class="address-legend" >
    <legend class="address-lable">Page Layout</legend>
    <table  class="address-table">
      <tbody>
        <tr>
          <td>

            Layout: </br>

            <%=ajax_select("custom_layout","product",@product, @product_layouts)%>            

          </td>
        </tr>
       
        </tr>
      </tbody>
    </table>
  </fieldset>
</div>

app/views/products/_picture_list.html.erb
<%# return if (not defined?(picture_list).nil?) %>
<% @pictures = picture_list if @pictures.blank? %>

<% @pictures.each do |picture| %>
<% puts("---------->  picture.file_name(): '#{picture.file_name()}'") %>
<%= render(:partial=>"picture_view.html" , :locals=>{:picture=>picture}) if not picture.file_name.blank? %>
<% end if not @pictures.blank?%>

app/views/products/product_search.json.erb
[
    <% @products.each do |product| %>
     {
     "id":"<%=  product.id%>",
     "label":"<%=  product.product_name.to_s + ': ' + product.product_description.to_s %>",
     "value":""
     }
     <% if @products.last!=product then %>
       ,
     <% end %>

<% end %>
  ]

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @product.product_id %>
</p>

<p>
  <b>Sku:</b>
  <%= @product.sku %>
</p>

<p>
  <b>Supplier product:</b>
  <%= @product.supplier_product_id %>
</p>

<p>
  <b>Product name:</b>
  <%= @product.product_name %>
</p>

<p>
  <b>Product description:</b>
  <%= @product.product_description %>
</p>

<p>
  <b>Supplier:</b>
  <%= @product.supplier_id %>
</p>

<p>
  <b>Department:</b>
  <%= @product.department_id %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_id %>
</p>

<p>
  <b>Quantity per unit:</b>
  <%= @product.quantity_per_unit %>
</p>

<p>
  <b>Unit size:</b>
  <%= @product.unit_size %>
</p>

<p>
  <b>Unit price:</b>
  <%= @product.unit_price %>
</p>

<p>
  <b>Msrp:</b>
  <%= @product.msrp %>
</p>

<p>
  <b>Product detail:</b>
  <%= @product.product_detail_id %>
</p>

<p>
  <b>Discount:</b>
  <%= @product.discount %>
</p>

<p>
  <b>Unit weight:</b>
  <%= @product.unit_weight %>
</p>

<p>
  <b>Units in stock:</b>
  <%= @product.units_in_stock %>
</p>

<p>
  <b>Units on order:</b>
  <%= @product.units_on_order %>
</p>

<p>
  <b>Reorder level:</b>
  <%= @product.reorder_level %>
</p>

<p>
  <b>Product active:</b>
  <%= @product.product_active %>
</p>

<p>
  <b>Discount available:</b>
  <%= @product.discount_available %>
</p>

<p>
  <b>Product ranking:</b>
  <%= @product.product_ranking %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>